// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXVyFyYDsJDAu9za9ZTm1qLO64fpkzg7M',
    appId: '1:1042133602783:web:7f31436283129518c5f46a',
    messagingSenderId: '1042133602783',
    projectId: 'cdautomation-v1',
    authDomain: 'cdautomation-v1.firebaseapp.com',
    storageBucket: 'cdautomation-v1.firebasestorage.app',
    measurementId: 'G-V0EN0389W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo8uY9F81Da6vpBx-XDol2r6yw25DRpEM',
    appId: '1:1042133602783:android:861965458f99feb6c5f46a',
    messagingSenderId: '1042133602783',
    projectId: 'cdautomation-v1',
    storageBucket: 'cdautomation-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbWO-ial_9Y6x4cvRNMmKjdWeojG0JRV8',
    appId: '1:1042133602783:ios:398e78423b52bacec5f46a',
    messagingSenderId: '1042133602783',
    projectId: 'cdautomation-v1',
    storageBucket: 'cdautomation-v1.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbWO-ial_9Y6x4cvRNMmKjdWeojG0JRV8',
    appId: '1:1042133602783:ios:398e78423b52bacec5f46a',
    messagingSenderId: '1042133602783',
    projectId: 'cdautomation-v1',
    storageBucket: 'cdautomation-v1.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXVyFyYDsJDAu9za9ZTm1qLO64fpkzg7M',
    appId: '1:1042133602783:web:cdcb884e1107bfa7c5f46a',
    messagingSenderId: '1042133602783',
    projectId: 'cdautomation-v1',
    authDomain: 'cdautomation-v1.firebaseapp.com',
    storageBucket: 'cdautomation-v1.firebasestorage.app',
    measurementId: 'G-BK8RSN1P2Z',
  );
}
